[versions]
android-plugin = "7.4.2"
kotlin = "1.8.10"
jetpack-core = "1.9.0"
appcompat = "1.6.1"
material = "1.8.0"
activity = "1.6.1"
fragment = "1.5.5"
constraintlayout = "2.1.4"
recyclerview = "1.2.1"
navigation = "2.5.3"
gson = "2.10.1"
junit = "4.13.2"
junit-ext = "1.1.5"
espresso = "3.5.1"